# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa37bafda733358a1627e5ae62367ffa4fe4388d0447f5bfa9ae190e84a0a16f5dd13ab55c735df9572be1a5adef6dd199a04e0c9a95d6c40df0545fdd26ed4

test:
  secret_key_base: caff5276fcbd7c55515ad3fb374a90236bee4c3d62896d0c5e2242e8a279cc91612eada5752458165f71639b21e518e5e1c3858b82d2b46d9c9eb2c08ad1dd66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
